expenses/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView
from .views import increase_counter
from .views import contact_form



urlpatterns = [
    path('', views.my_default_view, name='default_view'),
    path('financial-planning/', views.financial_planning, name='financial_planning'),
    path('reports-and-analytics/', views.reports_and_analytics, name='reports_and_analytics'),
    path('account-settings/', views.account_settings, name='account_settings'),
    path('support/', views.support, name='support'),
    path('register/', views.register, name='register'),
    path('login/', views.MyLoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('home/', views.my_default_view, name='home'),
    path('expense-list/', views.expense_list, name='expense_list'),  
    path('news1.html', views.news1_view, name='news1'), 
    path('news2.html', views.news2_view, name='news2'), 
    path('news3.html', views.news3_view, name='news3'), 
    path('news4.html', views.news4_view, name='news4'), 
    path('news5.html', views.news5_view, name='news5'), 
    path('news6.html', views.news6_view, name='news6'), 
    path('news7.html', views.news7_view, name='news7'), 
    path('news8.html', views.news8_view, name='news8'), 
    path('news9.html', views.news9_view, name='news9'), 
    path('news10.html', views.news10_view, name='news10'), 
    path('increase_counter/', increase_counter, name='increase_counter'),
    path('contact/', contact_form, name='contact_form'),
    path('finance_resources/', views.finance_resources, name='finance_resources'),
    path('tax_calculator/', views.tax_calculator, name='tax_calculator'),
    path('finance_resources/economy_tips.html', views.economy_tips_view, name='economy_tips'),
    path('review/', views.review_form, name='review_form'),
    path('capital/', views.capital, name='capital'),
    path('finance_resources/investment_tips.html', views.investment_tips_view, name='investment_tips'),
    path('finance_resources/investment2_tips.html', views.investment2_tips_view, name='investment2_tips'),

]
    

finance_manager/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('', include('expenses.urls')),   
]

expenses/models.py
# models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Expense(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField()

    def __str__(self):
        return self.name
    

class FinancialGoal(models.Model):
    name = models.CharField(max_length=255)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField()

    def __str__(self):
        return self.name

class News(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='news_images/', blank=True, null=True)

    def __str__(self):
        return self.title
    
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    registration_date = models.DateTimeField(auto_now_add=True)

class Analitics(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    name=models.CharField(max_length=100)
    amount=models.DecimalField(max_digits=10, decimal_places=2)
    date=models.DateTimeField(default=timezone.now)


class Visit(models.Model):
    count = models.PositiveIntegerField(default=0)

    def increment(self):
        self.count += 1
        self.save()

    def __str__(self):
        return str(self.count)
    
class FinancialResource(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    link = models.URLField()

    def __str__(self):
        return self.title
    

class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField()
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

expenses/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Review




class RegisterForm(UserCreationForm):
    username = forms.CharField(
        max_length=200,
        required = True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}),
    )
    email = forms.EmailField(
        max_length=100,
        required = False,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
    )
    password1 = forms.CharField(
        required = True,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}),
    )
    password2 = forms.CharField(
        required = True,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password Again'}),
    )
    check = forms.BooleanField(required = True)

    class Meta:
        model = User
        fields = [
            'username', 'email', 'password1', 'password2', 'check',
        ]
        

class expenseForm(forms.Form):
    expenseName = forms.CharField()
    expenseAmount = forms.IntegerField()

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'comment']

expenses/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from .models import  FinancialGoal, Expense, News
from django.core.paginator import Paginator
from django.contrib.auth.forms import UserCreationForm
from .models import *
from .forms import RegisterForm  
from django.contrib.auth.views import LoginView
from django.urls import reverse
from .models import Analitics 
from .models import Visit
from django.http import HttpResponse
from django.core.mail import send_mail
from django.http import JsonResponse
from .models import FinancialResource
from django.contrib.auth.decorators import login_required
from .forms import ReviewForm




def review_form(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('success_page')  # Redirect to a success page
    else:
        form = ReviewForm()
    
    return render(request, 'home.html', {'form': form})


def finance_resources(request):
    resources = FinancialResource.objects.all()
    return render(request, 'finance_resources.html', {'financial_resources': resources})

class MyLoginView(LoginView):
    template_name = 'login.html'


def logout_view(request):
    logout(request)
    return redirect(reverse('default_view'))

def register(request):
    if request.method == 'GET':
        form  = RegisterForm()
        context = {'form': form}
        return render(request, 'register.html', context)

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()

            login(request, user)

            return redirect('default_view')

        else:
            context = {'form': form}
            return render(request, 'register.html', context)

    return render(request, 'register.html', {})


def expense_list(request):
    expenses = Analitics.objects.all()  # Получаем все объекты Analitics
    if request.method != "POST":
        return render(request, 'expense-list.html', {'expenses': expenses})
    else:

        Analitics.objects.create(
            user=request.user, 
            name=request.POST["expenseName"],
            amount=request.POST["expenseAmount"],
            date =request.POST["deadline"],
        )
        
        return redirect("/")

def financial_planning(request):
    finances = FinancialGoal.objects.all()  # Получаем все объекты FinancialGoal
    if request.method != "POST":
        return render(request, 'financial-planning.html', {'finances': finances})
    else:
        FinancialGoal.objects.create(
            name=request.POST["finance_name"],
            amount=request.POST["target_amount"],
            date=request.POST["deadline"],
        )
        
        return redirect("/")

@login_required
def my_default_view(request):
    visit, created = Visit.objects.get_or_create(id=1)
    visit.increment()
    
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            Review.objects.create(
                user=request.user, 
                rating=int(request.POST.get("rating")),
                comment=request.POST.get("comment"),
            )
            return redirect(reverse("default_view"))  # Redirect to a success page
    else:
        form = ReviewForm()

    return render(request, 'home.html', {'visit_count': visit.count, "form": form, "reviews": Review.objects.all()})



@login_required
def reports_and_analytics(request):
    expenses = Analitics.objects.filter(user=request.user)
    finances = FinancialGoal.objects.all()

    context = {
        'expenses': expenses,
        'finances': finances,
    }

    return render(request, 'reports-and-analytics.html', context)



def account_settings(request):
    return render(request, 'account-settings.html')

def capital(request):
    return render(request, 'capital.html')

def support(request):
    return render(request, 'support.html')

def news1_view(request):
    return render(request, 'news1.html') 

def news2_view(request):
    return render(request, 'news2.html') 

def news3_view(request):
    return render(request, 'news3.html') 

def news4_view(request):
    return render(request, 'news4.html') 

def news5_view(request):
    return render(request, 'news5.html') 

def news6_view(request):
    return render(request, 'news6.html') 

def news7_view(request):
    return render(request, 'news7.html') 

def news8_view(request):
    return render(request, 'news8.html') 

def news9_view(request):
    return render(request, 'news9.html') 

def news10_view(request):
    return render(request, 'news10.html') 

def economy_tips_view(request):
    return render(request, 'economy_tips.html') 

def investment_tips_view(request):
    return render(request, 'investment_tips.html') 

def investment2_tips_view(request):
    return render(request, 'investment2_tips.html') 



def increase_counter(request):
    visit, created = Visit.objects.get_or_create(id=1)
    visit.increment()
    return render(request, 'home.html', {'visit_count': visit.count})

def increase_counter(request):
    visit, created = Visit.objects.get_or_create(id=1)
    visit.increment()
    return HttpResponse(str(visit.count))


def delete_expenses(request):
    if request.method == 'POST':
        selected_ids = request.POST.getlist('reports-and-analytics.html[]')  # Используйте фактическое имя, используемое в вашем шаблоне
        Expense.objects.filter(id__in=selected_ids).delete()
        # Предполагая, что вы хотите перенаправить после удаления, обновите URL по необходимости
        return redirect('expense-list')  # Обновите с фактическим именем URL
    return HttpResponse('Недопустимый метод запроса', status=400)

def edit_expense(request, expense_id):
    # Обработайте логику редактирования здесь
    # Предполагая, что вы хотите перенаправить после редактирования, обновите URL по необходимости
    return redirect('expense-list')  # Обновите с фактическим именем URL




def contact_form(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')

        # Отправляем электронное письмо
        send_mail(
            f'Сообщение от {name}',
            f'От: {email}\n\n{message}',
            'boris.nicolaec@mail.ru',  # Замените на ваш адрес электронной почты
            ['boris.nicolaec@mail.ru'],  # Замените на ваш адрес электронной почты
            fail_silently=False,
        )

        return JsonResponse({'status': 'success', 'message': 'Сообщение успешно отправлено!'})
    else:
        return JsonResponse({'status': 'error', 'message': 'Недопустимый метод запроса'})
    

def tax_calculator(request):
    if request.method == 'POST':
        income = float(request.POST.get('income'))
        # Здесь вы можете добавить вашу логику расчета налогов
        # Например, простой расчет 20% налога от дохода:
        tax_amount = 0.2 * income
        return render(request, 'tax_calculator.html', {'tax_amount': tax_amount})
    return render(request, 'tax_calculator.html')

expenses/templates/economy_tips.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Финансовая аналитика в бизнесе</title>
    <link rel="stylesheet" href="styles.css">
    <link rel="icon" href="/static/money_symbol_6068402.png" type="image/x-icon">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css" integrity="sha512-1cK78a1o+ht2JcaW6g8OXYwqpev9+6GqOkz9xmBN9iUUhIndKtxwILGWYOSibOKjLsEdjyjZvYDq/cZwNeak0w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style>
        /* Основной стиль */
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }

        .snowflakes {
            position: fixed;
            top: 0;
            left: 0;
            pointer-events: none;
            z-index: 9999;
        }

        .snowflake {
            position: absolute;
            width: 10px;
            height: 10px;
            background-color: #fff;
            border-radius: 50%;
            animation: snowfall linear infinite;
        }

        @keyframes snowfall {
            0% {
                transform: translateY(-50%);
            }
            100% {
                transform: translateY(100vh);
            }
        }

        /* Стили для статьи */
        .article {
            max-width: 800px;
            margin: 50px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        .article h2 {
            font-size: 2em;
            margin-bottom: 10px;
        }

        .article img {
            width: 100%;
            height: auto;
            margin-bottom: 20px;
            border-radius: 5px;
        }

        .article p {
            font-size: 1.1em;
            line-height: 1.6;
            margin-bottom: 20px;
        }

        .back-button {
            display: inline-block;
            padding: 8px 16px;
            background-color: #007bff;
            color: white;
            text-decoration: none;
            border-radius: 4px;
            transition: background-color 0.3s ease-in-out;
        }

        .back-button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="snowflakes" aria-hidden="true">
        <!-- Добавьте больше div'ов с классом "snowflake" для большего количества снежинок -->
        <div class="snowflake"></div>
        <div class="snowflake"></div>
        <div class="snowflake"></div>
    </div>

    <article class="article" data-aos="fade-up" data-aos-duration="3000">
        <h2>Советы по экономии денег</h2>
        <img src="{% static 'OIP.jpg' %}" alt="Изображение статьи">
        <p>
            Выберите подходящую финансовую аналитическую платформу с учетом потребностей вашего бизнеса и без избыточных функций, которые могут увеличить расходы. Обучите персонал эффективно использовать этот инструмент для снижения ошибок и экономии времени. Рассмотрите облачные сервисы, которые предлагают гибкие тарифы и масштабирование ресурсов по мере необходимости. Автоматизируйте процессы сбора и обработки данных для снижения человеческого фактора и повышения точности. Регулярно мониторьте и оптимизируйте использование платформы для экономии ресурсов. Используйте доступные бесплатные ресурсы аналитики данных и планирования финансов. Создайте бюджет и следите за его выполнением для более прозрачного финансового анализа и предотвращения излишних расходов.
        </p>
        <a href="#" class="back-button">Назад</a>
    </article>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const backButton = document.querySelector('.back-button');
            backButton.addEventListener('click', function(event) {
                event.preventDefault();
                window.location.href = 'http://127.0.0.1:8000/finance_resources/'; // Поменяйте на путь вашей главной страницы
            });
        });
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js" integrity="sha512-A7AYk1fGKX6S2SsHywmPkrnzTZHrgiVT7GcQkLGDe2ev0aWb8zejytzS8wjo7PGEXKqJOrjQ4oORtnimIRZBtw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        AOS.init();
    </script>
    <script>
        function createSnowflakes() {
            const snowflakeCount = 50; // Количество снежинок

            for (let i = 0; i < snowflakeCount; i++) {
                const snowflake = document.createElement('div');
                snowflake.className = 'snowflake';
                snowflake.style.left = Math.random() * window.innerWidth + 'px';
                snowflake.style.animationDuration = (Math.random() * 5 + 3) + 's';
                snowflake.style.animationDelay = -(Math.random() * 8) + 's';
                document.querySelector('.snowflakes').appendChild(snowflake);
            }
        }

        createSnowflakes();
    </script>
</body>
</html>

expenses/templates/expense-list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WalletWISE</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css" integrity="sha512-1cK78a1o+ht2JcaW6g8OXYwqpev9+6GqOkz9xmBN9iUUhIndKtxwILGWYOSibOKjLsEdjyjZvYDq/cZwNeak0w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="icon" href="\static\—Pngtree—money symbol_6068402.png" type="image/x-icon">
<style>
body {
  font-family: Arial, sans-serif;
  margin: 0;
  padding: 0;
  background-color: #f4f4f4;
}

.container {
  width: 80%;
  margin: 20px auto;
  background-color: #fff;
  padding: 20px;
  border-radius: 8px;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
}

h1 {
  text-align: center;
}

form {
  display: flex;
  flex-direction: column;
  max-width: 300px;
  margin: 0 auto;
}

label,
input {
  margin-bottom: 10px;
}

button {
  padding: 10px 20px;
  background-color: #e5ff00;
  color: #000000;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

button:hover {
  background-color: #939490;
}
.snowflakes {
            position: fixed;
            top: 0;
            left: 0;
            pointer-events: none;
            z-index: 9999;
         }

         .snowflake {
            position: absolute;
            width: 10px;
            height: 10px;
            background-color: #fff;
            border-radius: 50%;
            animation: snowfall linear infinite;
         }

         @keyframes snowfall {
            0% {
                transform: translateY(-50%);
            }
            100% {
                transform: translateY(100vh);
            }
         }
</style>
</head>
<body>
  <div class="snowflakes" aria-hidden="true">
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <!-- Добавьте больше div'ов с классом "snowflake" для большего количества снежинок -->
  </div>
  <header>
    <nav>
        <img src="{% static 'logo.jpg' %}" alt="logo" class="logo" />
        <ul>
            <li><a href="/">Главная</a></li>
            <li><a href="/expense-list">Список расходов</a></li>
            <li>
                <a href="/financial-planning"
                    >Финансовое планирование</a
                >
            </li>
            <li>
                <a href="/reports-and-analytics">Отчеты и аналитика</a>
            </li>
            <li>
                <a href="/finance_resources">Финансовая грамотность</a>
            </li>
            <li>
                <a href="/capital">накопления</a>
            </li>
            <li>
                <a href="/tax_calculator">
                    Инструмент для расчета налогов</a
                >
            </li>
            <li><a href="/support">Поддержка и обратная связь</a></li>
            <ul class="sidebar-nav">
                {% if user.is_authenticated %}
                <li>User: {{ user.get_username }}</li>
                <li><a href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                <li><a id="user" href="/register">Регистрация</a></li>
                |
                <li>
                    <a
                        id="user"
                        href="{% url 'login'%}?next={{request.path}}"
                        >Войти</a
                    >
                </li>
                {% endif %}
            </ul>
        </ul>
    </nav>
</header>
    <br>
    <br>
    <div class="container" data-aos="fade-up">
      <h1>Отслеживание расходов</h1>
      <form id="expenseForm" method="post">
        {% csrf_token %}
        <div>
          <label for="expenseName">Наименование расхода:</label>
          <input type="text" id="expenseName" name="expenseName" required>
        </div>
        <div>
          <label for="expenseAmount">Сумма расхода:</label>
          <input type="number" id="expenseAmount" name="expenseAmount" required>
        </div> 
        <div>
        <label for="deadline">Дата:</label>
        <input type="date" name="deadline" id="deadline" required><br>
        </div>
        <button type="submit">Добавить расход</button>
      </form>
         
      <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js" integrity="sha512-A7AYk1fGKX6S2SsHywmPkrnzTZHrgiVT7GcQkLGDe2ev0aWb8zejytzS8wjo7PGEXKqJOrjQ4oORtnimIRZBtw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script>
        AOS.init();

        </script>
                <script>
                  function createSnowflakes() {
        const snowflakeCount = 50; // Количество снежинок
      
        for (let i = 0; i < snowflakeCount; i++) {
          const snowflake = document.createElement('div');
          snowflake.className = 'snowflake';
          snowflake.style.left = Math.random() * window.innerWidth + 'px';
          snowflake.style.animationDuration = (Math.random() * 5 + 3) + 's';
          snowflake.style.animationDelay = -(Math.random() * 8) + 's';
          document.querySelector('.snowflakes').appendChild(snowflake);
        }
      }
      
      createSnowflakes();
              </script>

expenses/templates/register.html
<!DOCTYPE html>
<html lang="ru">

<head>
    <title>WalletWISE</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link rel="icon" href="\static\—Pngtree—money symbol_6068402.png" type="image/x-icon">
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Roboto Thin', sans-serif;
        }

        input {
            height: 45px;
            width: 100%;
            color: #385983;
            font-size: 14px;
            line-height: 16px;
            border: 2px solid #E9F2FF;
            border-radius: 5px;
            padding-left: 25px;
        }

        input:focus {
            outline: none;
            border: 2px solid #00378a;
        }

        main {
            background-image: url(photo1697416459.jpeg);
            background-size: cover;
            background-position: center;
            background-attachment: fixed;
            height: 100vh;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            position: relative;
        }

        .circle {
            position: absolute;
            z-index: 1;
            width: 2534px;
            height: 2534px;
            border-radius: 50%;
            background: #000000;
            box-shadow: 0px 4px 70px 6px rgba(217, 229, 255, 0.25);
            animation-name: fadeCircle;
            animation-duration: .7s;
            animation-timing-function: ease-in-out;
            animation-delay: .3s;
            animation-iteration-count: 1;
            animation-fill-mode: forwards;
        }

        @keyframes fadeCircle {
            0% {
                width: 2534px;
                height: 2534px;
            }

            25% {
                width: 2000px;
                height: 2000px;
            }

            50% {
                width: 1500px;
                height: 1500px;
            }

            75% {
                width: 1000px;
                height: 1000px;
            }

            100% {
                width: 534px;
                height: 534px;
            }
        }

        .register-form-container {
        opacity: 0;
        position: relative;
        z-index: 2;
        max-width: 250px; /* Уменьшаем максимальную ширину формы */
        width: 100%;
        background: #FFFFFF;
        box-shadow: 0px 6px 50px rgba(217, 229, 255, 0.7);
        border-radius: 20px;
        padding: 10px; /* Уменьшаем отступы внутри формы */
        animation-name: fadeForm;
        animation-duration: .7s;
        animation-timing-function: ease-in-out;
        animation-delay: 1.4s;
        animation-iteration-count: 1;
        animation-fill-mode: forwards;
    }
        @keyframes fadeForm {
            0% {
                opacity: 0;
            }

            25% {
                opacity: .25;
            }

            50% {
                opacity: .5;
            }

            75% {
                opacity: .75;
            }

            100% {
                opacity: 1;
            }
        }

        .form-title {
            color: #30507D;
            font-weight: 500;
            font-size: 20px;
            line-height: 23px;
            margin-bottom: 38px;
        }

        .form-field {
            margin-bottom: 13px;
        }

        .button {
            font-weight: bold;
            font-size: 14px;
            display: block;
            height: 35px;
            background: #ffffff;
            border-radius: 5px;
            color: #000000;
            text-transform: uppercase;
            text-align: center;
            line-height: 35px;
            cursor: pointer;
            border: none;
        }

        .button:hover {
            background-color: #a3a3a3;
        }

        a.button {
            text-decoration: none;
        }

        .button-google {
            color: #C6CFDC;
            background: #F2F6FF;
        }

        .button-google:hover {
            background: #E2E6F0;
            color: #fff;
        }

        .divider {
            font-weight: 500;
            font-size: 12px;
            line-height: 14px;
            color: #405D87;
            text-align: center;
            padding-top: 25px;
            padding-bottom: 25px;
        }

        #id_check{
            height: auto;
            
        }    
        .snowflakes {
            position: fixed;
            top: 0;
            left: 0;
            pointer-events: none;
            z-index: 9999;
         }

         .snowflake {
            position: absolute;
            width: 10px;
            height: 10px;
            background-color: #fff;
            border-radius: 50%;
            animation: snowfall linear infinite;
         }

         @keyframes snowfall {
            0% {
                transform: translateY(-50%);
            }
            100% {
                transform: translateY(100vh);
            }
         }

         
        </style>
</head>

<body>
    <div class="snowflakes" aria-hidden="true">
        <div class="snowflake"></div>
        <div class="snowflake"></div>
        <div class="snowflake"></div>
        <!-- Добавьте больше div'ов с классом "snowflake" для большего количества снежинок -->
      </div>
    <main>
        <div class="circle"></div>
        <div class="register-form-container">
            <div class="row justify-content-center">
                    <h2 class="mb-4">Register</h2>
                    <form method="post">
                        {% csrf_token %}
                        {{ form }}
                        <button type="submit" class=" mt-3 button">Register</button>
                    </form>

                    <div class="mt-3">
                        <a href="{% url 'login' %}" class="button">Back to login</a>
                    </div>
                    <div class="mt-3">
                        <a href="{% url 'home' %}" class="button">Back to Home</a>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <script>
        function createSnowflakes() {
const snowflakeCount = 50; // Количество снежинок

for (let i = 0; i < snowflakeCount; i++) {
const snowflake = document.createElement('div');
snowflake.className = 'snowflake';
snowflake.style.left = Math.random() * window.innerWidth + 'px';
snowflake.style.animationDuration = (Math.random() * 5 + 3) + 's';
snowflake.style.animationDelay = -(Math.random() * 8) + 's';
document.querySelector('.snowflakes').appendChild(snowflake);
}
}

createSnowflakes();
    </script>
</body>

</html>